package com.example.slfastenermobileapp.model.putaway

data class ResponseObjectX(
    val barcode: String?,
    val blockedQty: Double?,
    val description: String?,
    val expiryDate: String?,
    val grnId: Int?,
    val internalBatchNo: String?,
    val isActive: Boolean?,
    val isExpirable: Boolean?,
    val isPutAwayDone: Boolean?,
    val isQCRequired: Boolean?,
    val isSaleBlocked: Boolean?,
    val itemCategory: String?,
    val itemCode: String?,
    val itemGroup: String?,
    val itemName: String?,
    val itemPrice: Double?,
    val locationId: Int?,
    val mhType: String?,
    val parentChildLinkedIds: String?,
    val qcStatus: String?,
    val qtyBlockRemarks: String?,
    val qtyBlockedBy: String?,
    val qtyForSale: Double?,
    val qtyReleaseDate: String?,
    val saleBlockedBy: String?,
    val stockInAt: String?,
    val stockItemBatches: List<Any>?,
    val stockItemId: Int?,
    val stockQty: Int,
    val supplierBatchNo: String?,
    val uom: String?
)